### ISSUE TITLE
section header

### ISSUE THREAD

**Issue by AYB-cmd** [AYB-cmd/contre__la--montre#1]
svp! veuillez vérifier votre responsivity et aligner le texte mrc. @terbouchi

**Comment by terbouchi** [comment]
fixed

**Comment by terbouchi** [comment]
Fixed; 
Veuillez voir le " updated header" branch dev

**Comment by BOUKRIM** [comment]
bon travail. merci pour votre  participation

**Comment by AYB-cmd** [comment]
👍
